class RaceTrack {
  constructor(
    trackLength,
    trackLocation,
    trackLogo,
    trackPhoto,
    trackIcon,
    trackFacts,
    trackName,
    trackCoords,
  ) {
    this.trackLength = trackLength;
    this.trackLocation = trackLocation;
    this.trackLogo = trackLogo;
    this.trackPhoto = trackPhoto;
    this.trackIcon = trackIcon;
    this.trackFacts = trackFacts;
    this.trackName = trackName;
    this.trackGeo = [trackCoords[0], trackCoords[1]];
    this.URL = `https://api.open-meteo.com/v1/forecast?latitude=${this.trackGeo[0]}&longitude=${this.trackGeo[1]}&hourly=temperature_2m,precipitation_probability,wind_speed_10m,wind_gusts_10m,precipitation,weather_code,cloud_cover&timezone=America%2FNew_York&wind_speed_unit=mph&temperature_unit=fahrenheit&precipitation_unit=inch`;
  }

  async get7DayWeather() {
    try {
      // fetch data
      const res = await fetch(this.URL);
      const data = await res.json();

      return data;
    } catch (error) {
      console.log(error);
    }
  }
}
// <------------------check the images
const tracks = {
  Atlanta: new RaceTrack(
    "1.54 mile",
    "Hampton, GA",
    "./assets/echo_park_speedway.webp",
    "./assets/atlanta_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1960",
      "<span>Banking:</span><br>28deg",
      "<span>2026 winners:</span><br>Tyler Reddick",
    ],
    "Echopark Speedway",
    ["33.3813", "-84.3160"],
  ),
  Bristol: new RaceTrack(
    ".533 mile",
    "Bristol, TN",
    "./assets/bristol.webp",
    "./assets/bristol_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1961",
      "<span>Banking:</span><br>Prog. 24-28deg",
      "<span>2025 Winners:</span><br>Kyle Larson<br>Christopher Bell",
    ],
    "Bristol Motor Speedway",
    ["36.5159", "-82.2571"],
  ),
  Charlotte: new RaceTrack(
    "1.5 mile",
    "Concord, NC",
    "./assets/charlotte.webp",
    "./assets/charlotte_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1960",
      "<span>Banking:</span><br>24deg in turns<br>5deg on straights",
      "<span>2025 Winners:</span><br>Ross Chastain<br>Shane van Gisbergen",
    ],
    "Charlotte Motor Speedway",
    ["35.3516", "-80.6848"],
  ),
  Chicagoland: new RaceTrack(
    "1.5 mile",
    "Joliet, IL",
    "./assets/chicagoland.webp",
    "./assets/chicagoland_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>2001",
      "<span>Banking:</span><br>18deg in turns<br>11deg on frontstretch",
      "<span>2019 Winner:</span><br>Alex Bowman",
    ],
    "Chicagoland Speedway",
    ["41.4747", "-88.0572"],
  ),
  COTA: new RaceTrack(
    "2.4 mile",
    "Austin, TX",
    "./assets/cota.webp",
    "./assets/cota_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>2012",
      "20 turn road course",
      "<span>2026 winners:</span><br>Tyler Reddick",
    ],
    "Circuit Of The Americas",
    ["30.1329", "-97.6375"],
  ),
  Darlington: new RaceTrack(
    "1.366 mile",
    "Darlington, SC",
    "./assets/darlington.webp",
    "./assets/darlington_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1950",
      "<span>Banking:</span><br>25deg in 1 and 2<br>23deg in 3 and 4",
      "<span>2025 Winners:</span><br>Denny Hamlin<br>Chase Briscoe",
    ],
    "Darlington Raceway",
    ["34.2952", "-79.9063"],
  ),
  Daytona: new RaceTrack(
    "2.5 mile",
    "Daytona Beach, FL",
    "./assets/daytona.webp",
    "./assets/daytona_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1959",
      "<span>Banking:</span><br>31deg in the turns<br>18deg in the tri-oval",
      "<span>2026 winners:</span><br>Tyler Reddick",
    ],
    "Daytona International Speedway",
    ["29.1852", "-81.0700"],
  ),
  Dover: new RaceTrack(
    "1 mile",
    "Dover, DE",
    "./assets/dover.webp",
    "./assets/dover_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1969",
      "<span>Banking:</span><br>24deg in turns<br>9deg on straights",
      "<span>2025 Winner:</span><br>Denny Hamlin",
    ],
    "Dover Motor Speedway",
    ["39.1901", "-75.5306"],
  ),
  GrandPrixOfStPetersburg: new RaceTrack(
    "1.8 mile",
    "St. Petersburg, FL",
    "./assets/st_petes.webp",
    "./assets/st_petes_top_view.webp",
    "image3",
    [
      "Inaugural event was in 1985",
      "14 turn street course",
      "<span>2026 Winner:</span><br>Layne Riggs",
    ],
    "The Firestone Grand Prix of St. Petersburg",
    ["27.7667", "-82.6333"],
  ),
  Homestead: new RaceTrack(
    "1.5 mile",
    "Homestead, FL",
    "./assets/homestead.webp",
    "./assets/homestead_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1995",
      "<span>Banking:</span><br>Variable 18-20deg in turns<br>3deg on straights",
      "<span>2025 Winner:</span><br>Kyle Larson",
    ],
    "Homestead-Miami Speedway",
    ["25.4510", "-80.4081"],
  ),
  Indy: new RaceTrack(
    "2.5 mile",
    "Speedway, IN",
    "./assets/indy.webp",
    "./assets/indy_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1909",
      "<span>Banking:</span><br>9deg in turns",
      "Originally paved with 3.2 million bricks",
      "<span>2025 Winner:</span><br>Bubba Wallace",
    ],
    "The Indianapolis Motor Speedway",
    ["39.7953", "-86.2348"],
  ),
  Iowa: new RaceTrack(
    ".875 mile",
    "Newton, IA",
    "./assets/iowa.webp",
    "./assets/iowa_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>2006",
      "<span>Banking:</span><br>variable 12-14deg in turns<br>4-11deg on frontstretch",
      "<span>2025 Winner:</span><br>William Byron",
    ],
    "Iowa Speedway",
    ["41.6791", "-93.0031"],
  ),
  IRP: new RaceTrack(
    // Indianapolis Raceway Park
    "0.686 mile",
    "Brownsburg, IN",
    "./assets/irp.webp",
    "./assets/irp_top_view.webp",
    "image3",
    [
      "<span>Opened:</span><br>1960",
      "<span>Banking:</span><br>7-12 deg in the turns",
      "<span>2025 Winner:</span><br>Layne Riggs",
    ],
    "Lucas Oil Indianapolis Raceway Park",
    ["39.812778", "-86.340833"],
  ),
  Kansas: new RaceTrack(
    "1.5 mile",
    "Kansas City, KS",
    "./assets/kansas.webp",
    "./assets/kansas_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>2001",
      "<span>Banking:</span><br>17-20deg in turns<br>9-11deg on frontstretch",
      "<span>2025 Winners:</span><br>Kyle Larson<br>Chase Elliot",
    ],
    "Kansas Speedway",
    ["39.1159", "-94.8334"],
  ),
  LasVegas: new RaceTrack(
    "1.5 mile",
    "Las Vegas, NV",
    "./assets/las_vegas.webp",
    "./assets/las_vegas_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1996",
      "<span>Banking:</span><br>20deg in turns<br>9-12deg on straightaways",
      "<span>2025 Winners:</span><br>Josh Berry<br>Denny Hamlin",
    ],
    "Las Vegas Motor Speedway",
    ["36.2733", "-115.0113"],
  ),
  LimeRock: new RaceTrack(
    "1.5 mile",
    "Lakeville, CT",
    "./assets/lime_rock.webp",
    "./assets/lime_rock_top_view.webp",
    "image3",
    [
      "<span>Opened:</span><br>1957",
      "7 turn road course",
      "<span>2025 Winner:</span><br>Corey Heim",
    ],
    "Lime Rock Park",
    ["41.93", "-73.39"],
  ),
  Martinsville: new RaceTrack(
    ".526 mile",
    "Ridgeway, VA",
    "./assets/martinsville.webp",
    "./assets/martinsville_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1947",
      "<span>Banking:</span><br>12deg in the turns",
      "<span>2025 Winners:</span><br>Denny Hamlin<br>William Byron",
    ],
    "Martinsville Speedway",
    ["36.6536", "-79.8517"],
  ),
  Michigan: new RaceTrack(
    "2 mile",
    "Brooklyn, MI",
    "./assets/michigan.webp",
    "./assets/michigan_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1968",
      "<span>Banking:</span><br>18deg in turns<br>12deg on frontstretch",
      "<span>2025 Winner:</span><br>Denny Hamlin",
    ],
    "Michigan International Speedway",
    ["42.0654", "-84.2389"],
  ),
  Nashville: new RaceTrack(
    "1.33 mile",
    "Lebanon, TN",
    "./assets/nashville.webp",
    "./assets/nashville_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>2001",
      "<span>Banking:</span><br>14deg in the turns",
      "<span>2025 Winner:</span><br>Ryan Blaney",
    ],
    "Nashville Superspeedway",
    ["36.1426", "-86.3533"],
  ),
  NewHampshire: new RaceTrack(
    "1.058 mile",
    "Loudon, NH",
    "./assets/new_hampshire.webp",
    "./assets/new_hampshire_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1990",
      "<span>Banking:</span><br>2-7deg in turns",
      "<span>2025 Winner:</span><br>Ryan Blaney",
    ],
    "New Hampshire Motor Speedway",
    ["43.3617", "-71.4650"],
  ),
  NorthWilkesboro: new RaceTrack(
    ".625 mile",
    "North Wilkesboro, NC",
    "./assets/north_wilkesboro.webp",
    "./assets/north_wilkesboro_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1947",
      "<span>Banking:</span><br>13deg in the turns",
      "<span>1996 Winner:</span><br>Jeff Gordon",
    ],
    "North Wilkesboro Speedway",
    ["36.1426", "-81.0730"],
  ),
  Phoenix: new RaceTrack(
    "1 mile",
    "Avondale, AZ",
    "./assets/phoenix.webp",
    "./assets/phoenix_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1964",
      "<span>Banking:</span><br>8-9deg in 1 and 2<br>11deg in 3 and 4",
      "<span>2025 Winners:</span><br>Christopher Bell<br>Ryan Blaney",
    ],
    "Phoenix Raceway",
    ["33.3756", "-112.3116"],
  ),
  Pocono: new RaceTrack(
    "2.5 mile",
    "Long Pond, PA",
    "./assets/pocono.webp",
    "./assets/pocono_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1969",
      "<span>Banking:</span><br>14deg, 8deg, 6deg<br>in turns 1, 2, 3",
      "<span>2025 Winner:</span><br>Chase Briscoe",
    ],
    "Pocono Raceway",
    ["41.0553", "-75.5100"],
  ),
  Richmond: new RaceTrack(
    ".75 mile",
    "Henrico County, VA",
    "./assets/richmond.webp",
    "./assets/richmond_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1946",
      "<span>Banking:</span><br>14deg in turns<br>8deg on frontstretch<br>2deg on backstretch",
      "<span>2025 Winner:</span><br>Austin Dillon",
    ],
    "Richmond Raceway",
    ["37.5939", "-77.4206"],
  ),
  Rockingham: new RaceTrack(
    "0.94 mile",
    "Richmond County, NC",
    "./assets/rockingham.webp",
    "./assets/rockingham_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1965",
      "<span>Banking:</span><br>22deg in 1 and 2<br>25deg in 3 and 4",
      "<span>2004 Winner:</span><br>Matt Kenseth",
    ],
    "Rockingham Speedway",
    ["34.97418", "-79.61042"],
  ),
  SanDiego: new RaceTrack(
    "3.4 mile",
    "San Diego, CA",
    "./assets/san_diego.webp",
    "./assets/san_diego_top_view.webp",
    "image path",
    ["For the U.S. Navy's 250th anniversary", "16 turn street course"],
    "Naval Base Coronado",
    ["32.6991", "-117.2152"],
  ),
  Sonoma: new RaceTrack(
    "2.52 mile",
    "Sonoma, CA",
    "./assets/sonoma.webp",
    "./assets/sonoma_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1968",
      "12 turn road course",
      "<span>2025 Winner:</span><br>Shane van Gisbergen",
    ],
    "Sonoma Raceway",
    ["38.1631", "-122.4597"],
  ),
  Talladega: new RaceTrack(
    "2.66 mile",
    "Lincoln, AL",
    "./assets/talladega.webp",
    "./assets/talladega_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1969",
      "<span>Banking:</span><br>33deg in turns",
      "<span>2025 Winners:</span><br>Austin Cindric<br>Chase Briscoe",
    ],
    "Talledega Superspeedway",
    ["33.5673", "-86.0671"],
  ),
  Texas: new RaceTrack(
    "1.5 mile",
    "Fort Worth, TX",
    "./assets/texas.webp",
    "./assets/texas_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1997",
      "<span>Banking:</span><br>20deg in 1 and 2<br>24deg in 3 and 4<br>5deg on straights",
      "<span>2025 Winner:</span><br>Joey Logano",
    ],
    "Texas Motor Speedway",
    ["33.0367", "-97.2828"],
  ),
  WatkinsGlen: new RaceTrack(
    "2.45 mile",
    "Watkins Glen, NY",
    "./assets/watkins_glen.webp",
    "./assets/watkins_glen_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1948",
      "7 turn road course",
      "<span>2025 Winner:</span><br>Shane van Gisbergen",
    ],
    "Watkins Glen International",
    ["42.3333", "-76.9236"],
  ),
  WorldWideTech: new RaceTrack(
    "1.25 mile",
    "Madison, IL",
    "./assets/wwtr.webp",
    "./assets/wwtr_top_view.webp",
    "image path",
    [
      "<span>Opened:</span><br>1997",
      "<span>Banking:</span><br>11deg in 1 and 2<br>9deg in 3 and 4",
      "<span>2025 Winner:</span><br>Denny Hamlin",
    ],
    "World Wide Technology Raceway",
    ["38.6513", "-90.1364"],
  ),
};

export default tracks;
