class RaceTrack {
  constructor(
    trackLength,
    trackLocation,
    trackLogo,
    trackPhoto,
    trackIcon,
    trackFacts,
    trackName,
    trackCoords,
  ) {
    this.trackLength = trackLength;
    this.trackLocation = trackLocation;
    this.trackLogo = trackLogo;
    this.trackPhoto = trackPhoto;
    this.trackIcon = trackIcon;
    this.trackFacts = trackFacts;
    this.trackName = trackName;
    this.trackGeo = [trackCoords[0], trackCoords[1]];
    this.URL = `https://api.open-meteo.com/v1/forecast?latitude=${this.trackGeo[0]}&longitude=${this.trackGeo[1]}&hourly=temperature_2m,precipitation_probability,wind_speed_10m,wind_gusts_10m,precipitation,weather_code,cloud_cover&timezone=America%2FNew_York&wind_speed_unit=mph&temperature_unit=fahrenheit&precipitation_unit=inch`;
  }

  async get7DayWeather() {
    try {
      // fetch data
      const res = await fetch(this.URL);
      const data = await res.json();

      return data;
    } catch (error) {
      console.log(error);
    }
  }
}
// <------------------check the images
const tracks = {
  Daytona: new RaceTrack(
    "2.5 mile",
    "Daytona Beach, FL",
    "./assets/daytona.webp",
    "./assets/daytona_top_view.webp",
    "image path",
    ["opened in 1959", "31deg banking in the turns, 18deg in the tri-oval"],
    "Daytona International Speedway",
    ["29.1852", "-81.0700"],
  ),
  Atlanta: new RaceTrack(
    "1.54 mile",
    "Hampton, GA",
    "./assets/echo_park_speedway.webp",
    "./assets/atlanta_top_view.webp",
    "image path",
    ["opened in 1960", "28deg banking"],
    "Echopark Speedway",
    ["33.3813", "-84.3160"],
  ),
  COTA: new RaceTrack(
    "3.41 mile",
    "Austin, TX",
    "./assets/cota.webp",
    "./assets/cota_top_view.webp",
    "image path",
    ["opened in 2012", "has 20 turns"],
    "Circuit Of The Americas",
    ["30.1329", "-97.6375"],
  ),
  Phoenix: new RaceTrack(
    "1 mile",
    "Avondale, AZ",
    "./assets/phoenix.webp",
    "./assets/phoenix_top_view.webp",
    "image path",
    ["opened in 1964", "reconfigured in 2018"],
    "Phoenix Raceway",
    ["33.3756", "-112.3116"],
  ),
  LasVegas: new RaceTrack( // <----left off here with redoing the logos
    "1.5 mile",
    "Las Vegas, NV",
    "./assets/las_vegas.png",
    "./assets/las_vegas_top_view.webp",
    "image path",
    ["opened in 1996", "20deg banking in turns, 9-12deg on straightaways"],
    "Las Vegas Motor Speedway",
    ["36.2733", "-115.0113"],
  ),
  Darlington: new RaceTrack(
    "1.366 mile",
    "Darlington, SC",
    "./assets/darlington.webp",
    "./assets/darlington_top_view.webp",
    "image path",
    ["opened in 1950", "25deg banking in 1 and 2, 23deg in 3 and 4"],
    "Darlington Raceway",
    ["34.2952", "-79.9063"],
  ),
  Martinsville: new RaceTrack(
    ".526 mile",
    "Ridgeway, VA",
    "./assets/martinsville.png",
    "./assets/martinsville_top_view.webp",
    "image path",
    ["opened in 1947", "12deg banking"],
    "Martinsville Speedway",
    ["36.6536", "-79.8517"],
  ),
  Bristol: new RaceTrack(
    ".533 mile",
    "Bristol, TN",
    "./assets/bristol.webp",
    "./assets/bristol_top_view.webp",
    "image path",
    ["opened in 1961", "24-28deg prog banking in turns"],
    "Bristol Motor Speedway",
    ["36.5159", "-82.2571"],
  ),
  Kansas: new RaceTrack(
    "1.5 mile",
    "Kansas City, KS",
    "./assets/kansas.png",
    "./assets/kansas_top_view.webp",
    "image path",
    ["opened in 2001", "17-20deg banking in turns, 9-11deg on frontstretch"],
    "Kansas Speedway",
    ["39.1159", "-94.8334"],
  ),
  Talladega: new RaceTrack(
    "2.66 mile",
    "Lincoln, AL",
    "./assets/talladega.webp",
    "./assets/talladega_top_view.webp",
    "image path",
    ["opened in 1969", "33deg banking in turns"],
    "Talledega Superspeedway",
    ["33.5673", "-86.0671"],
  ),
  Texas: new RaceTrack(
    "1.5 mile",
    "Fort Worth, TX",
    "./assets/texas.png",
    "./assets/texas_top_view.webp",
    "image path",
    [
      "opened in 1997",
      "20deg banking in 1 and 2, 24deg in 3 and 4, 5deg on straights",
    ],
    "Texas Motor Speedway",
    ["33.0367", "-97.2828"],
  ),
  WatkinsGlen: new RaceTrack(
    "2.45 mile",
    "Watkins Glen, NY",
    "./assets/watkins_glen.webp",
    "./assets/watkins_glen_top_view.webp",
    "image path",
    ["opened in 1948", "141 ft elevation change in the esses"],
    "Watkins Glen International",
    ["42.3333", "-76.9236"],
  ),
  Dover: new RaceTrack(
    "1 mile",
    "Dover, DE",
    "./assets/dover.png",
    "./assets/dover_top_view.webp",
    "image path",
    ["opened in 1969", "24deg banking in turns, 9deg on straights"],
    "Dover Motor Speedway",
    ["39.1901", "-75.5306"],
  ),
  Charlotte: new RaceTrack(
    "1.5 mile",
    "Concord, NC",
    "./assets/charlotte.webp",
    "./assets/charlotte_top_view.webp",
    "image path",
    ["opened in 1960", "24deg banking in turns, 5deg on straights"],
    "Charlotte Motor Speedway",
    ["35.3516", "-80.6848"],
  ),
  Nashville: new RaceTrack(
    "1.33 mile",
    "Lebanon, TN",
    "./assets/nashville.webp",
    "./assets/nashville_top_view.webp",
    "image path",
    ["opened in 2001", "14deg banking in the turns"],
    "Nashville Superspeedway",
    ["36.1426", "-86.3533"],
  ),
  Michigan: new RaceTrack(
    "2 mile",
    "Brooklyn, MI",
    "./assets/michigan.png",
    "./assets/michigan_top_view.webp",
    "image path",
    ["opened in 1968", "18deg banking in turns 12deg on frontstretch"],
    "Michigan International Speedway",
    ["42.0654", "-84.2389"],
  ),
  Pocono: new RaceTrack(
    "2.5 mile",
    "Long Pond, PA",
    "./assets/pocono.webp",
    "./assets/pocono_top_view.webp",
    "image path",
    ["opened in 1969", "14deg, 8deg, 6deg banking in turns 1, 2, 3"],
    "Pocono Raceway",
    ["41.0553", "-75.5100"],
  ),
  SanDiego: new RaceTrack(
    "3.4 mile",
    "San Diego, CA",
    "./assets/san_diego.webp",
    "./assets/san_diego_top_view.webp",
    "image path",
    ["for the U.S. Navy's 250th anniversary", "16 turns"],
    "Naval Base Coronado",
    ["32.6991", "-117.2152"],
  ),
  Sonoma: new RaceTrack(
    "2.52 mile",
    "Sonoma, CA",
    "./assets/sonoma.png",
    "./assets/sonoma_top_view.webp",
    "image path",
    ["opened in 1968", "12 turns"],
    "Sonoma Raceway",
    ["38.1631", "-122.4597"],
  ),
  Chicagoland: new RaceTrack(
    "1.5 mile",
    "Joliet, IL",
    "./assets/chicagoland.png",
    "./assets/chicagoland_top_view.webp",
    "image path",
    ["opened in 2001", "18deg banking in turns, 11deg on frontstretch"],
    "Chicagoland Speedway",
    ["41", "-88"],
  ),
  NorthWilkesboro: new RaceTrack(
    ".625 mile",
    "North Wilkesboro, NC",
    "./assets/north_wilkesboro.webp",
    "./assets/north_wilkesboro_top_view.webp",
    "image path",
    ["opened in 1947", "13deg banking in the turns"],
    "North Wilkesboro Speedway",
    ["36.1426", "-81.0730"],
  ),
  Indy: new RaceTrack(
    "2.5 mile",
    "Speedway, IN",
    "./assets/indy.png",
    "./assets/indy_top_view.webp",
    "image path",
    ["opened in 1909", "originally paved with 3.2 million bricks"],
    "The Indianapolis Motor Speedway",
    ["39.7953", "-86.2348"],
  ),
  Iowa: new RaceTrack(
    ".875 mile",
    "Newton, IA",
    "./assets/iowa.webp",
    "./assets/iowa_top_view.webp",
    "image path",
    [
      "opened in 2006",
      "variable banking 12-14deg in turns, 4-11deg on frontstretch",
    ],
    "Iowa Speedway",
    ["41.6791", "-93.0031"],
  ),
  Richmond: new RaceTrack(
    ".75 mile",
    "Henrico County, VA",
    "./assets/richmond.png",
    "./assets/richmond_top_view.webp",
    "image path",
    [
      "opened in 1946",
      "14deg banking in turns, 8deg on frontstretch, 2deg on backstretch",
    ],
    "Richmond Raceway",
    ["37.5939", "-77.4206"],
  ),
  NewHampshire: new RaceTrack(
    "1.058 mile",
    "Loudon, NH",
    "./assets/new_hampshire.png",
    "./assets/new_hampshire_top_view.webp",
    "image path",
    ["opened in 1990", "2-7deg banking in turns, 1deg on straights"],
    "New Hampshire Motor Speedway",
    ["43.3617", "-71.4650"],
  ),
  WorldWideTech: new RaceTrack(
    "1.25 mile",
    "Madison, IL",
    "./assets/wwtr.png",
    "./assets/wwtr_top_view.webp",
    "image path",
    ["opened in 1997", "11deg banking in 1 and 2, 9deg in 3 and 4"],
    "World Wide Technology Raceway",
    ["38.6513", "-90.1364"],
  ),
  Homestead: new RaceTrack(
    "1.5 mile",
    "Homestead, FL",
    "./assets/homestead.png",
    "./assets/homestead_top_view.webp",
    "image path",
    ["opened in 1995", "variable 18-20deg banking in turns, 3deg on straights"],
    "Homestead-Miami Speedway",
    ["25.4510", "-80.4081"],
  ),
};

export default tracks;
