class RaceTrack {
  constructor(
    trackLength,
    trackLocation,
    trackLogo,
    trackPhoto,
    trackIcon,
    trackFacts,
    trackName,
    trackCoords,
  ) {
    this.trackLength = trackLength;
    this.trackLocation = trackLocation;
    this.trackLogo = trackLogo;
    this.trackPhoto = trackPhoto;
    this.trackIcon = trackIcon;
    this.trackFacts = trackFacts;
    this.trackName = trackName;
    this.trackGeo = [trackCoords[0], trackCoords[1]];
    this.URL = `https://api.open-meteo.com/v1/forecast?latitude=${this.trackGeo[0]}&longitude=${this.trackGeo[1]}&hourly=temperature_2m,precipitation_probability,wind_speed_10m,wind_gusts_10m,precipitation,weather_code,cloud_cover&timezone=America%2FNew_York&wind_speed_unit=mph&temperature_unit=fahrenheit&precipitation_unit=inch`;
  }

  async get7DayWeather() {
    try {
      // fetch data
      const res = await fetch(this.URL);
      const data = await res.json();

      return data;
    } catch (error) {
      console.log(error);
    }
  }
}
// <------------------check the images
const tracks = {
  Atlanta: new RaceTrack(
    "1.54 mile",
    "Hampton, GA",
    "./assets/echo_park_speedway.webp",
    "./assets/atlanta_top_view.webp",
    "image path",
    ["opened in 1960", "28deg banking", "2026 winners:\nTyler Reddick"],
    "Echopark Speedway",
    ["33.3813", "-84.3160"],
  ),
  Bristol: new RaceTrack(
    ".533 mile",
    "Bristol, TN",
    "./assets/bristol.webp",
    "./assets/bristol_top_view.webp",
    "image path",
    [
      "opened in 1961",
      "24-28deg prog banking in turns",
      "2025 Winners:\nKyle Larson\nChristopher Bell",
    ],
    "Bristol Motor Speedway",
    ["36.5159", "-82.2571"],
  ),
  Charlotte: new RaceTrack(
    "1.5 mile",
    "Concord, NC",
    "./assets/charlotte.webp",
    "./assets/charlotte_top_view.webp",
    "image path",
    [
      "opened in 1960",
      "24deg banking in turns, 5deg on straights",
      "2025 Winners:\nRoss Chastain\nShane van Gisbergen",
    ],
    "Charlotte Motor Speedway",
    ["35.3516", "-80.6848"],
  ),
  Chicagoland: new RaceTrack(
    "1.5 mile",
    "Joliet, IL",
    "./assets/chicagoland.webp",
    "./assets/chicagoland_top_view.webp",
    "image path",
    [
      "opened in 2001",
      "18deg banking in turns, 11deg on frontstretch",
      "2019 Winner:\nAlex Bowman",
    ],
    "Chicagoland Speedway",
    ["41", "-88"],
  ),
  COTA: new RaceTrack(
    "2.4 mile",
    "Austin, TX",
    "./assets/cota.webp",
    "./assets/cota_top_view.webp",
    "image path",
    ["opened in 2012", "20 turn road course", "2026 winners:\nTyler Reddick"],
    "Circuit Of The Americas",
    ["30.1329", "-97.6375"],
  ),
  Darlington: new RaceTrack(
    "1.366 mile",
    "Darlington, SC",
    "./assets/darlington.webp",
    "./assets/darlington_top_view.webp",
    "image path",
    [
      "opened in 1950",
      "25deg banking in 1 and 2, 23deg in 3 and 4",
      "2025 Winners:\nDenny Hamlin\nChase Briscoe",
    ],
    "Darlington Raceway",
    ["34.2952", "-79.9063"],
  ),
  Daytona: new RaceTrack(
    "2.5 mile",
    "Daytona Beach, FL",
    "./assets/daytona.webp",
    "./assets/daytona_top_view.webp",
    "image path",
    [
      "opened in 1959",
      "31deg banking in the turns, 18deg in the tri-oval",
      "2026 winners:\nTyler Reddick",
    ],
    "Daytona International Speedway",
    ["29.1852", "-81.0700"],
  ),
  Dover: new RaceTrack(
    "1 mile",
    "Dover, DE",
    "./assets/dover.webp",
    "./assets/dover_top_view.webp",
    "image path",
    [
      "opened in 1969",
      "24deg banking in turns, 9deg on straights",
      "2025 Winner:\nDenny Hamlin",
    ],
    "Dover Motor Speedway",
    ["39.1901", "-75.5306"],
  ),
  GrandPrixOfStPetersburg: new RaceTrack(
    "1.8 mile",
    "St. Petersburg, FL",
    "./assets/st_petes.webp",
    "./assets/st_petes_top_view.webp",
    "image3",
    [
      "inaugural event was 1985",
      "14 turn street course",
      "2026 Winner:\nLayne Riggs",
    ],
    "The Firestone Grand Prix of St. Petersburg",
    ["27.7667", "-82.6333"],
  ),
  Homestead: new RaceTrack(
    "1.5 mile",
    "Homestead, FL",
    "./assets/homestead.webp",
    "./assets/homestead_top_view.webp",
    "image path",
    [
      "opened in 1995",
      "variable 18-20deg banking in turns, 3deg on straights",
      "2025 Winner:\nKyle Larson",
    ],
    "Homestead-Miami Speedway",
    ["25.4510", "-80.4081"],
  ),
  Indy: new RaceTrack(
    "2.5 mile",
    "Speedway, IN",
    "./assets/indy.webp",
    "./assets/indy_top_view.webp",
    "image path",
    [
      "opened in 1909",
      "9deg banking in turns",
      "originally paved with 3.2 million bricks",
      "2025 Winner:\nBubba Wallace",
    ],
    "The Indianapolis Motor Speedway",
    ["39.7953", "-86.2348"],
  ),
  Iowa: new RaceTrack(
    ".875 mile",
    "Newton, IA",
    "./assets/iowa.webp",
    "./assets/iowa_top_view.webp",
    "image path",
    [
      "opened in 2006",
      "variable banking 12-14deg in turns, 4-11deg on frontstretch",
      "2025 Winner:\nWilliam Byron",
    ],
    "Iowa Speedway",
    ["41.6791", "-93.0031"],
  ),
  IRP: new RaceTrack(
    // Indianapolis Raceway Park
    "0.686 mile",
    "Brownsburg, IN",
    "./assets/irp.webp",
    "./assets/irp_top_view.webp",
    "image3",
    [
      "opened in 1960",
      "7-12 deg banking in the turns",
      "2025 Winner:\nLayne Riggs",
    ],
    "Lucas Oil Indianapolis Raceway Park",
    ["39.812778", "-86.340833"],
  ),
  Kansas: new RaceTrack(
    "1.5 mile",
    "Kansas City, KS",
    "./assets/kansas.webp",
    "./assets/kansas_top_view.webp",
    "image path",
    [
      "opened in 2001",
      "17-20deg banking in turns, 9-11deg on frontstretch",
      "2025 Winners:\nKyle Larson\nChase Elliot",
    ],
    "Kansas Speedway",
    ["39.1159", "-94.8334"],
  ),
  LasVegas: new RaceTrack(
    "1.5 mile",
    "Las Vegas, NV",
    "./assets/las_vegas.webp",
    "./assets/las_vegas_top_view.webp",
    "image path",
    [
      "opened in 1996",
      "20deg banking in turns, 9-12deg on straightaways",
      "2025 Winners:\nJosh Berry\nDenny Hamlin",
    ],
    "Las Vegas Motor Speedway",
    ["36.2733", "-115.0113"],
  ),
  LimeRock: new RaceTrack(
    "1.5 mile",
    "Lakeville, CT",
    "./assets/lime_rock.webp",
    "./assets/lime_rock_top_view.webp",
    "image3",
    ["opened in 1957", "7 turn road course", "2025 Winner:\nCorey Heim"],
    "Lime Rock Park",
    ["41.93", "-73.39"],
  ),
  Martinsville: new RaceTrack(
    ".526 mile",
    "Ridgeway, VA",
    "./assets/martinsville.webp",
    "./assets/martinsville_top_view.webp",
    "image path",
    [
      "opened in 1947",
      "12deg banking in the turns",
      "2025 Winners:\nDenny Hamlin\nWilliam Byron",
    ],
    "Martinsville Speedway",
    ["36.6536", "-79.8517"],
  ),
  Michigan: new RaceTrack(
    "2 mile",
    "Brooklyn, MI",
    "./assets/michigan.webp",
    "./assets/michigan_top_view.webp",
    "image path",
    [
      "opened in 1968",
      "18deg banking in turns 12deg on frontstretch",
      "2025 Winner:\nDenny Hamlin",
    ],
    "Michigan International Speedway",
    ["42.0654", "-84.2389"],
  ),
  Nashville: new RaceTrack(
    "1.33 mile",
    "Lebanon, TN",
    "./assets/nashville.webp",
    "./assets/nashville_top_view.webp",
    "image path",
    [
      "opened in 2001",
      "14deg banking in the turns",
      "2025 Winner:\nRyan Blaney",
    ],
    "Nashville Superspeedway",
    ["36.1426", "-86.3533"],
  ),
  NewHampshire: new RaceTrack(
    "1.058 mile",
    "Loudon, NH",
    "./assets/new_hampshire.webp",
    "./assets/new_hampshire_top_view.webp",
    "image path",
    ["opened in 1990", "2-7deg banking in turns", "2025 Winner:\nRyan Blaney"],
    "New Hampshire Motor Speedway",
    ["43.3617", "-71.4650"],
  ),
  NorthWilkesboro: new RaceTrack(
    ".625 mile",
    "North Wilkesboro, NC",
    "./assets/north_wilkesboro.webp",
    "./assets/north_wilkesboro_top_view.webp",
    "image path",
    [
      "opened in 1947",
      "13deg banking in the turns",
      "1996 Winner:\nJeff Gordon",
    ],
    "North Wilkesboro Speedway",
    ["36.1426", "-81.0730"],
  ),
  Phoenix: new RaceTrack(
    "1 mile",
    "Avondale, AZ",
    "./assets/phoenix.webp",
    "./assets/phoenix_top_view.webp",
    "image path",
    [
      "Opened: 1964",
      "Banking:\n8-9deg in 1 and 2\n11deg in 3 and 4",
      "2025 Winners:\nChristopher Bell\nRyan Blaney",
    ],
    "Phoenix Raceway",
    ["33.3756", "-112.3116"],
  ),
  Pocono: new RaceTrack(
    "2.5 mile",
    "Long Pond, PA",
    "./assets/pocono.webp",
    "./assets/pocono_top_view.webp",
    "image path",
    [
      "opened in 1969",
      "14deg, 8deg, 6deg banking in turns 1, 2, 3",
      "2025 Winner:\nChase Briscoe",
    ],
    "Pocono Raceway",
    ["41.0553", "-75.5100"],
  ),
  Richmond: new RaceTrack(
    ".75 mile",
    "Henrico County, VA",
    "./assets/richmond.webp",
    "./assets/richmond_top_view.webp",
    "image path",
    [
      "opened in 1946",
      "14deg banking in turns, 8deg on frontstretch, 2deg on backstretch",
      "2025 Winner:\nAustin Dillon",
    ],
    "Richmond Raceway",
    ["37.5939", "-77.4206"],
  ),
  Rockingham: new RaceTrack(
    "0.94 mile",
    "Richmond County, NC",
    "./assets/rockingham.webp",
    "./assets/rockingham_top_view.webp",
    "image path",
    [
      "opened in 1965",
      "22deg banking in 1 and 2, 25deg in 3 and 4",
      "2004 Winner:\nMatt Kenseth",
    ],
    "Rockingham Speedway",
    ["34.97418", "-79.61042"],
  ),
  SanDiego: new RaceTrack(
    "3.4 mile",
    "San Diego, CA",
    "./assets/san_diego.webp",
    "./assets/san_diego_top_view.webp",
    "image path",
    ["for the U.S. Navy's 250th anniversary", "16 turn street course"],
    "Naval Base Coronado",
    ["32.6991", "-117.2152"],
  ),
  Sonoma: new RaceTrack(
    "2.52 mile",
    "Sonoma, CA",
    "./assets/sonoma.webp",
    "./assets/sonoma_top_view.webp",
    "image path",
    [
      "opened in 1968",
      "12 turn road course",
      "2025 Winner:\nShane van Gisbergen",
    ],
    "Sonoma Raceway",
    ["38.1631", "-122.4597"],
  ),
  Talladega: new RaceTrack(
    "2.66 mile",
    "Lincoln, AL",
    "./assets/talladega.webp",
    "./assets/talladega_top_view.webp",
    "image path",
    [
      "opened in 1969",
      "33deg banking in turns",
      "2025 Winners:\nAustin Cindric\nChase Briscoe",
    ],
    "Talledega Superspeedway",
    ["33.5673", "-86.0671"],
  ),
  Texas: new RaceTrack(
    "1.5 mile",
    "Fort Worth, TX",
    "./assets/texas.webp",
    "./assets/texas_top_view.webp",
    "image path",
    [
      "opened in 1997",
      "20deg banking in 1 and 2, 24deg in 3 and 4, 5deg on straights",
      "2025 Winner:\nJoey Logano",
    ],
    "Texas Motor Speedway",
    ["33.0367", "-97.2828"],
  ),
  WatkinsGlen: new RaceTrack(
    "2.45 mile",
    "Watkins Glen, NY",
    "./assets/watkins_glen.webp",
    "./assets/watkins_glen_top_view.webp",
    "image path",
    [
      "opened in 1948",
      "7 turn road course",
      "2025 Winner:\nShane van Gisbergen",
    ],
    "Watkins Glen International",
    ["42.3333", "-76.9236"],
  ),
  WorldWideTech: new RaceTrack(
    "1.25 mile",
    "Madison, IL",
    "./assets/wwtr.webp",
    "./assets/wwtr_top_view.webp",
    "image path",
    [
      "opened in 1997",
      "11deg banking in 1 and 2, 9deg in 3 and 4",
      "2025 Winner:\nDenny Hamlin",
    ],
    "World Wide Technology Raceway",
    ["38.6513", "-90.1364"],
  ),
};

export default tracks;
