const weatherCodes = {
  0: "Clear Sky",
  1: "Mainly Clear",
  2: "Partly Cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Fog",
  51: "Light Drizzle",
  53: "Moderate Drizzle",
  55: "Dense Drizzle",
  56: "Light Freezing Drizzle",
  57: "Dense Freezing Drizzle",
  61: "Light Rain",
  63: "Moderate Rain",
  65: "Heavy Rain",
  66: "Light Freezing Rain",
  67: "Heavy Freezing Rain",
  71: "Light Snow",
  73: "Moderate Snow",
  75: "Heavy Snow",
  77: "Snow Flurries",
  80: "Light Rain Showers",
  81: "Moderate Rain Showers",
  82: "Heavy Rain Showers",
  85: "Light Snow Showers",
  86: "Heavy Snow Showers",
  95: "Light to Moderate Thunderstorms",
  96: "Thunderstorms with Light Hail",
  99: "Thunderstorms with Heavy Hail",
};

export default weatherCodes;
